### PR TITLE
Fix graphing of changes

### PR DESCRIPTION
**Pull request by smyru**
Reading the FreeBSD Quaterly status report I have decided to take a look at the reported graph issue. Here are my findings:

* first it imports more than just the core of flot plugin
* fixes for PHP code to return conformant JSON data, otherwise newer jQuery will silently bail out
* make use of the aforementioned changes.

I was able to confirm on a hand crafted test env with static snapshots, that the non bar graphs load fine.

### CODE REVIEW

**Comment by dlangille** [comment]
Thank you, I will look at this ASAP. I greatly appreciate your effort on this.

**Comment by smyru** [comment]
Please note, it has been a while since I had written PHP code, so I am not sure, how your env would treat these changes. I would not be surprised if there were some warnings or incompatibilities with newer PHP versions.

**Comment by dlangille** [comment]
Thank you, this is a big help

This diff has been applied to https://dev.freshports.org/graphs2.php

Most graphs work. 

The other stuff might be just database queries.

I also notice the numbers at the bottom of the screen don't make any sense.

Where does `jquery.canvaswrapper.js` come from? For when I need to update it.

I'm guessing `jquery.flot.uiConstants.js` is just local for FreshPorts. Cheers.

**Comment by smyru** [comment]
Yeah, I should have noted this in the commit description. Now while I read the 1555fc1c summary, it sounds somewhat ambiguous. :-/ 

Anyway all of the aforementioned commit files are part of the [flot codebase](https://github.com/flot/flot/tree/master/source). So they are covered by the same licence as flot.

**Comment by dlangille** [comment]
For future reference, when I want to update these files:

- https://raw.githubusercontent.com/flot/flot/master/source/jquery.canvaswrapper.js
- https://raw.githubusercontent.com/flot/flot/master/source/jquery.colorhelpers.js
- https://raw.githubusercontent.com/flot/flot/master/source/jquery.flot.browser.js
- https://raw.githubusercontent.com/flot/flot/master/source/jquery.flot.drawSeries.js
- https://raw.githubusercontent.com/flot/flot/master/source/jquery.flot.js
- https://raw.githubusercontent.com/flot/flot/master/source/jquery.flot.saturated.js
- https://raw.githubusercontent.com/flot/flot/master/source/jquery.flot.uiConstants.js

**Comment by dlangille** [comment]
This went into release 1.50 and is now in production. Thank you.

**Pull request merged**
