### PR TITLE
FAQ: add/modify anchors, and a terser section about anchors

### PR DESCRIPTION
**Pull request by grahamperrin**
`<a id="anchors">` and more, to complement https://github.com/FreshPorts/freshports/commit/9572b879e71964ad18a674a9130373c122fe7b5b 

`#message` is effective; `#pkg-message` is not. 

Re: `id` in lieu of `name`: <https://www.w3.org/TR/html401/struct/links.html> and answers to <https://stackoverflow.com/q/484719/38108> – I hope I understand correctly.

### CODE REVIEW

**Comment by grahamperrin** [comment]
Under https://www.freshports.org/faq.php#anchors

I'm tempted to mention the **Display #Anchors** browser extension: 

* https://github.com/Rob--W/display-anchors#readme

**Comment by dlangille** [comment]
> Under https://www.freshports.org/faq.php#anchors
> 
> I'm tempted to mention the **Display #Anchors** browser extension:

Do

**Comment by grahamperrin** [comment]
Thanks. Done.

**Comment by grahamperrin** [comment]
Need to reposition the anchors to work within a table; and `</a>` close things. My bad, I should have tested before submitting the PR. 

image

I'll fix.

**Comment by grahamperrin** [comment]
… also need to think about PHP whilst fixing? I'll try.

**Pull request merged**
