### PR TITLE
www/opensearch.php: Echo XML declaration

### PR DESCRIPTION
**Pull request by tobiasmboelz**
Echo XML declaration for compatibility with PHP's [short open tag option](https://www.php.net/manual/en/ini.core.php#ini.short-open-tag).

### CODE REVIEW

**Comment by dlangille** [comment]
I manually copied this fix into production.  Please test.

**Comment by tobiasmboelz** [comment]
It works in Firefox, LibreWolf and Edge.

**Comment by tobiasmboelz** [comment]
Works in some old version of Safari (15.6.1), too.

**Comment by dlangille** [comment]
Thanks. I'll merge this soon. I'm at the beach.

**Comment by dlangille** [comment]
Sponsored by: Wrightsville Beach family vacation

**Comment by dlangille** [comment]
Now in production.

**Pull request merged**
