### PR TITLE
Remove distfiles

### PR DESCRIPTION
**Pull request by cpets**
This is deprecated so no point is linking to it.
http://people.freebsd.org/~ehaupt/distilator

I don't know if this is the correct way but I think it is.

### CODE REVIEW

**Comment by dlangille** [comment]
If you can, please dig farther into the code:

* Look for references to DISTFILESSURVEYURL in the code
* Remove code which references it.

thank you

**Comment by dlangille** [comment]
related to https://github.com/FreshPorts/freshports/issues/11

**Comment by cpets** [comment]
Hi, I will do that later. Thanks

**Comment by dlangille** [comment]
Thanks.

**Comment by cpets** [comment]
% find freshports -name "*.php" -exec grep "DISTFILESSURVEYURL" {} +
freshports/include/freshports.php:DEFINE('DISTFILESSURVEYURL',  'http://people.freebsd.org/~ehaupt/distilator/');
freshports/include/freshports.php:      return '<a href="' . DISTFILESSURVEYURL . urlencode($Category) . '/' . urlencode($Port) . '/" title="Distfiles Availability">Distfiles Availability</a>';
%

Which is the only files I edited ?

**Comment by dlangille** [comment]
The function freshports_DistFilesSurveyURL() has been removed.  That is appropriate.

What about code which calls freshports_DistFilesSurveyURL()?

**Comment by cpets** [comment]
Yeah guess I should of looked harder but DISTFILESSURVEY != freshports_DistFilesSurveyURL.

**Comment by dlangille** [comment]
Agreed.  They are not the same.  Current patch will break existing code.  I won't have time soon to look at this.  BSDCan / PGCon are peak right now.

**Comment by dlangille** [comment]
If we leave this open, it serves as a reminder.

**Pull request closed without merging**
