### PR TITLE
OpenSearch support

### PR DESCRIPTION
**Pull request by tobiasmboelz**
This pull request adds [OpenSearch](https://en.wikipedia.org/wiki/OpenSearch) support, providing an easy way for users to add FreshPorts as a search engine to their browser[^1].

[^1]: Or in case of Firefox, allowing them to add it at all, as the ability to define custom search engines was removed.

### CODE REVIEW

**Comment by dlangille** [comment]
I have this checked out on a non-public FreshPorts instance - I'm trying to add that website as a search engine to Safari.

I see the `link rel="search"` in the web page source.

I don't see how my web browser is set to use that.

**Comment by tobiasmboelz** [comment]
As far as I can tell, in Safari it is supposed to be automatically added to ["Quick Website Search"](https://developer.apple.com/library/archive/releasenotes/General/WhatsNewInSafari/Articles/Safari_8_0.html) (and not as regular search engine). But don't ask me how to use it, then.

**Comment by tobiasmboelz** [comment]
In Firefox, it shows up in the address bar menu(?) and the search engine can be added from there.

image

**Comment by dlangille** [comment]
@tobiasmboelz this is now in production. Can you verify it is acting as expected please?

**Comment by fvcc-rowens** [comment]
Trying to view https://www.freshports.org/opensearch.php directly appears to give a PHP error:


> Parse error: syntax error, unexpected identifier "version" in /usr/local/www/freshports/www/opensearch.php on line 2

FWLIW, I was able to feed the code to php locally (NOT via a web server) and other than the missing variables, it produced an OpenSearchDescription XML fragment as expected:

> <?xml version="1.0"?>
> <OpenSearchDescription xmlns="http://a9.com/-/spec/opensearch/1.1/">
>   <ShortName>FreshPorts</ShortName>
>   <Image width="16" height="16" type="image/x-icon">
> Notice: Undefined index: HTTP_HOST in /usr/home/rowens/opensearch.php on line 5
> 
> Call Stack:
>     0.0001     222344   1. {main}() /usr/home/rowens/opensearch.php:0
> 
> https:///favicon.ico</Image>
>   <Url type="text/html" template="
> Notice: Undefined index: HTTP_HOST in /usr/home/rowens/opensearch.php on line 6
> 
> Call Stack:
>     0.0001     222344   1. {main}() /usr/home/rowens/opensearch.php:0
> 
> https:///search.php?query={searchTerms}" />
> </OpenSearchDescription>
> 

FWIW, I'm guessing the web server is not handling that URL correctly - probably need a config change to fix the problem.  HTH!

**Comment by tobiasmboelz** [comment]
Yes, it looks like the web server is treating `<?xml …`  as PHP, probably because of the [short_open_tag](https://www.php.net/manual/en/ini.core.php#ini.short-open-tag) option. Either, this option has to be disabled, or line 2 in opensearch.php has to be replaced with a php echo statement as a workaround:

```php
<?php echo '<?xml version="1.0"?>'; ?>
```

**Comment by tobiasmboelz** [comment]
As short open tags are actually used at two places in the code base, I opened a new pull request with the necessary change (#588).

**Pull request merged**
