### PR TITLE
Switch to HTML5

### PR DESCRIPTION
**Pull request by jethron**
There's a few visual changes, mostly whitespace where I couldn't easily replicate the quirks stylesheet correctly. But otherwise I think it's pretty close, and [we're valid HTML5](https://validator.w3.org/nu/?doc=https%3A%2F%2Fa.freshports.org%2F) for most public pages after this.

Still todo are the pages that require a login (my environment is in maintenance mode so I need to change that and create a user to get to those pages and verify).

But with this is in place we'll be able to use all the new element types and hopefully start removing some of the nested tables used for layout.

### CODE REVIEW

**Comment by dlangille** [comment]
> Still todo are the pages that require a login (my environment is in maintenance mode so I need to change that and create a user to get to those pages and verify).

Maintenance mode no longer in effect.

**Comment by dlangille** [comment]
This is now on https://testgit.freshports.org/ & https://stagegit.freshports.org - after your review, I'll push it to production.

**Comment by jethron** [comment]
Thanks. Are we able to clean up the HTML include for `stats.html`? Should be the same as the vulnerabilities include, just removing the width and align attributes.

I'm working through some of the pages that were hidden in maintenance mode now; it would be nice to hold off until they're done too, but if that blocks other changes from hitting prod it looks OK to me at the moment and should be safe to go out.

**Comment by dlangille** [comment]
Yes, we can clean that up.  It's part of the backend code. 

See https://gist.github.com/dlangille/ddd1491c298ea42569983c0d059d09d8

**Pull request merged**
