### PR TITLE
Link URLs in commit messages

### PR DESCRIPTION
**Pull request by smortex**
These commits turn URLs in clickable links and also make problem reports accessible by one click.

### CODE REVIEW

**Comment by dlangille** [comment]
I have not forgotten.  I need to test it here first.

**Comment by dlangille** [comment]
I'll pull this into https://dev.freshports.org/ first.

Once you see it there, please show me two URLs, one from dev, one from prod, so we can test and compare.

**Comment by dlangille** [comment]
Does not seem to work for the PR here on 31 March: https://dev.freshports.org/cad/zcad/

**Comment by smortex** [comment]
Back from holidays… Adding a `/m` should fix this issue if it's a multi-line problem.  I'll open another PR for trying this!

**Pull request merged**
